- name: Add Redis repository to sources
  ansible.builtin.deb822_repository:
    name: redis
    uris: https://packages.redis.io/deb
    signed_by: https://packages.redis.io/gpg
    types: 
      - deb
      - deb-src
    components:
      - main
    suites:
      - "{{ ansible_distribution_release }}"
    architectures: amd64
    state: present

- name: Install redis
  ansible.builtin.apt:
    update_cache: true
    state: present
    name: "{{ item }}"
  with_items:
    - redis
    - redis-tools

- name: Enable ufw, open SSH port
  community.general.ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "6379"

- name: Start redis server
  ansible.builtin.systemd:
    name: redis-server
    state: started
    enabled: true

- name: Change redis password
  ansible.builtin.lineinfile:
    path: "{{ redis_config }}"
    regexp: "#?\\s*requirepass"
    line: "requirepass {{redis_password | mandatory}}"
  notify:
    - Restart redis