apiVersion: v1
kind: Namespace
metadata:
  name: events-organiser
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http-gateway
  namespace: events-organiser
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-router
  namespace: events-organiser
spec:
  parentRefs:
  - name: http-gateway
    namespace: events-organiser
  hostnames:
  - "{{ domain_name }}" # TODO: jinja2 template
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/events
    backendRefs:
    - name: events-public-svc
      port: 80