- name: Install WGET
  ansible.builtin.dnf:
    name: wget
    state: latest

- name: Install pre-requisites
  ansible.builtin.pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 

- name: Create temporary downloads directory /tmp/ansible/dls/
  ansible.builtin.file: 
    state: directory 
    path: "/tmp/ansible/dls/"

- name: Download Cosign v2.4.0 binary for x64
  ansible.builtin.get_url:
    url: "https://github.com/sigstore/cosign/releases/download/v2.4.0/cosign-linux-amd64"
    dest: "/tmp/ansible/dls/cosign"

- name: Download jq v1.7.1 binary for x64
  ansible.builtin.get_url:
    url: "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64"
    dest: "/tmp/ansible/dls/jq"

- name: Copy cosign to bin folder
  ansible.builtin.copy: 
    remote_src: True 
    src: "/tmp/ansible/dls/cosign" 
    dest: "/usr/local/bin/cosign"
    mode: "0755"

- name: Copy jq to bin folder
  ansible.builtin.copy: 
    remote_src: True 
    src: "/tmp/ansible/dls/cosign" 
    dest: "/usr/local/bin/cosign"
    mode: "0755"

- name: Remove downloaded files
  ansible.builtin.file: 
    path: "/tmp/ansible/dls" 
    state: absent

- name: Apply knative operator configuration
  kubernetes.core.k8s:
    state: present
    src: "https://github.com/knative/operator/releases/download/knative-v1.15.4/operator.yaml"