- name: Add MongoDB to repos
  ansible.builtin.yum_repository:
    name: mongodb
    description: "MongoDB repository"
    baseurl: "https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/"
    gpgkey: "https://pgp.mongodb.com/server-7.0.asc"
    gpgcheck: true
    enabled: true

- name: Install MongoDB
  ansible.builtin.dnf:
    name: "mongodb-org"
    state: latest
  notify:
  - Restart mongodb

- name: Open MySQL ports
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    port: "{{ item }}"
    state: enabled
  with_items:
    - 27017/tcp
    - 27017/udp

- name: Start mongod
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true