- name: Install/update httpd (apache)
  ansible.builtin.dnf:
    name: httpd
    state: latest
  notify:
    - Restart apache

- name: Open HTTP(s) ports
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    port: "{{ item }}"
    state: enabled
  with_items:
    - 80/tcp
    - 80/udp
    - 443/tcp
    - 443/udp

- name: Restart firewall service
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Security harden Apache with mod_security
  ansible.builtin.import_tasks:
    file: apache_mod_security.yml

- name: Start apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
