- hosts: controller
  user: centos
  become_user: root
  become: yes

  collections:
    - devsec.hardening

  vars:
    events_webserver_loc: "/srv/www/events_webserver"
    fqdn: "cs.ut.ee"
    set_mysql_password: false
  vars_files:
    - vault.yml

  roles:
    #- setup
    #- update_packages
    #- apache
    #- mysql_install
    #- name: devsec.hardening.mysql_hardening
    #  mysql_user_home: "/root/.my.cnf"
    #- rabbitmq_centos_install
    - redis_centos_install

- hosts: workers
  user: centos
  become_user: root
  become: yes

  collections:
    - devsec.hardening

  vars:
    llm_webserver_loc: /srv/www/llm_api_webserver
    fqdn: "cs.ut.ee"

  roles:
    - setup
    - update_packages
