- hosts: controller
  user: centos
  become_user: root
  become: yes

  vars:
    mysql_socket: "/var/lib/mysql/mysql.sock"
    redis_config: "/etc/redis/redis.conf"
  vars_files:
    - vault.yml

  roles:
    #- setup
    #- update_packages
    #- apache
    #- kubernetes_centos
    #- mysql
    #- rabbitmq_centos
    - redis_centos

- hosts: workers
  user: centos
  become_user: root
  become: yes

  vars:
    llm_webserver_loc: /srv/www/llm_api_webserver
    fqdn: "cs.ut.ee"

  roles:
    - setup
    - update_packages
    - kubernetes_centos
