- hosts: webserver
  user: centos
  become_user: root
  become: yes

  collections:
    - devsec.hardening

  vars:
    events_webserver_loc: "/srv/www/events_webserver"
    fqdn: "cs.ut.ee"
    set_mysql_password: false

  roles:
    - knative
    #- mysql_install
    #- mongodb_install
    #- devsec.hardening.mysql_hardening
    #- update_packages
    #- apache
    #- webserver_setup

- hosts: llm_server
  user: centos
  become_user: root
  become: yes

  collections:
    - devsec.hardening

  vars:
    llm_webserver_loc: /srv/www/llm_api_webserver
    fqdn: "cs.ut.ee"

  roles:
    #- update_packages
    #- setup
    #- apache
    #- llm_server_setup
