- name: Create ConfigMap & Secret for events organiser microservices
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'general-conf.yml') | from_yaml_all }}"

- name: Deploy HTTPRoute for the app
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'gateway-and-routing.yml') | from_yaml_all }}"

- name: Deploy public events microservice
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'events-public-deploy.yml') | from_yaml_all }}"

- name: Deploy private events microservice
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'events-private-deploy.yml') | from_yaml_all }}"

- name: Deploy public auth microservice
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'auth-public-deploy.yml') | from_yaml_all }}"

- name: Deploy public Microsoft accounts microservice
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'microsoft-public-deploy.yml') | from_yaml_all }}"