- name: Install NGINX directly on VM
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Remove default configuration for NGINX
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/main-site.conf
    state: absent

- name: Copy NGINX configuration to VM 
  ansible.builtin.template:
    src: main-site.conf
    dest: /etc/nginx/sites-enabled/main-site.conf
    user: root
    group: root
    mode: "0755"

- name: Reload service NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded