- name: Install/update MySQL
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
  with_items:
  - "mysql"
  - "mysql-server"
  notify:
  - Restart mysql

- name: Open MySQL ports
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    port: "{{ item }}"
    state: enabled
  with_items:
    - 3306/tcp
    - 3306/udp

- name: Install pymysql for MySQL hardening
  ansible.builtin.pip:
    name: pymysql
    state: present

- name: Start mysqld
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true

- name: Set .my.cnf with credentials
  template:
    src: 'my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: root
    group: mysql
    mode: '0440'