- name: Check for updates
  ansible.builtin.dnf:
    name: "*"
    state: latest
  register: updates_result

- name: Autoremove packages
  ansible.builtin.dnf:
    autoremove: true

- name: Check if server needs rebooting
  ansible.builtin.command:
    cmd: "dnf needs-restarting -r"
  register: reg_reboot_required
  ignore_errors: yes
  failed_when: false
  changed_when: reg_reboot_required.rc != 0
  notify:
  - Reboot server
