- name: Add kubernetes repo to yum repos
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
    enabled: true

- name: Install kubernetes
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "kubectl"
    - "kubeadm"