- name: Add kubernetes repo to yum repos
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
    enabled: true
    exclude: 
      - kubelet 
      - kubeadm 
      - kubectl 
      - cri-tools 
      - kubernetes-cni

- name: Add CRI-O repo
  ansible.builtin.yum_repository:
    name: cri-o
    description: CRI-O
    baseurl: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.32/rpm/
    gpgcheck: true
    gpgkey: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.32/rpm/repodata/repomd.xml.key
    enabled: true

# FROM: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# Setting SELinux in permissive mode by running setenforce 0 and sed ... effectively disables it. 
# This is required to allow containers to access the host filesystem; for example, some cluster network plugins require that. 
# You have to do this until SELinux support is improved in the kubelet.
- name: Put SELinux into permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Update SELinux config
  ansible.builtin.command:
    cmd: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Install kubernetes and cri-o
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  with_items:
    - "kubectl"
    - "kubeadm"
    - "kubelet"
    - "container-selinux"
    - "cri-o"

- name: Open kubernetes default ports
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    port: "{{ item }}"
    state: enabled
  with_items:
    - "5473/tcp"
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250/tcp"
    - "10251/tcp"
    - "10252/tcp"
    - "10255/tcp"

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true

- name: Disable swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

- name: Enable CRI-O
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: true