- name: Install necessary packages for Python
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items:
    - flask
    - requests  # could probably be needed
    - tensorflow # required to run LLM models on our server
  tags:
    - py_webserver

- name: Make directory for webserver files
  ansible.builtin.file:
    path: "{{ llm_webserver_loc }}"
    state: directory
    owner: centos
    group: centos
    mode: 0755
  tags:
    - py_webserver

- name: Copy server files over as ZIP
  ansible.builtin.copy:
    src: server.zip
    dest: "{{ llm_webserver_loc }}/server.zip"
  tags:
    - py_webserver

- name: Unzip server files
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ llm_webserver_loc }}/server.zip"
    dest: "{{ llm_webserver_loc }}"
  tags:
    - py_webserver

- name: Delete the copied ZIP file
  ansible.builtin.file:
    state: absent
    path: "{{ llm_webserver_loc }}/server.zip"
  tags:
    - py_webserver
