- hosts: controller
  user: ubuntu
  become_user: root
  become: yes

  vars:
    mysql_socket: "/var/lib/mysql/mysql.sock"
    redis_config: "/etc/redis/redis.conf"
    domain_name: "www.11072100.xyz"
    is_kube_master_node: true

    events_org_config:

  vars_files:
    - vault.yml

  roles:
    #- update_packages
    #- setup
    #- rabbitmq
    #- kubernetes
    #- mysql
    #- redis
    - app_setup_kubernetes

- hosts: workers
  user: ubuntu
  become_user: root
  become: yes

  vars_files:
    - vault.yml

  roles:
    #- update_packages
    #- setup
    #- kubernetes
