- hosts: controller
  user: ubuntu
  become_user: root
  become: yes

  vars:
    mysql_socket: "/var/lib/mysql/mysql.sock"
    redis_config: "/etc/redis/redis.conf"
    domain_name: "www.11072100.xyz"
    is_kube_master_node: true
  vars_files:
    - vault.yml

  roles:
    - update_packages
    - setup
    - rabbitmq
    - kubernetes
    - mysql
    - redis

- hosts: workers
  user: ubuntu
  become_user: root
  become: yes

  vars_files:
    - vault.yml

  roles:
    #- update_packages
    #- setup
    #- kubernetes
    #- mysql
    - rabbitmq
    - redis
