- name: Add kubernetes repo to yum/dnf
  ansible.builtin.yum_repository:
    name: "kubernetes"
    description: "Kubernetes 1.32"
    enabled: true
    gpgcheck: true
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key"
    baseurl: "https://pkgs.k8s.io/core:/stable:/v1.32/rpm/"

- name: Install a few core modules
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - "python3"
    - "python3-pip"
    - "firewalld"
    - "unzip"
    - "nano"
    - "kubectl"
  notify:
    - Restart server

- name: Start firewall service
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
    daemon_reload: true
    
#- name: Drive to mount
#  ansible.builtin.pause:
#    prompt: "Write the name of the drive to mount"
#    echo: true
#  register: drive_name

#- name: Format the drive
#  ansible.builtin.pause:
#    prompt: "Format the drive before proceeding"

#- name: Mount data drive for the system
#  ansible.posix.mount:
#    boot: true
#    fstype: ext4
#    path: /mnt/data_drive
#    src: "{{ drive_name.user_input }}"
#    state: mounted
#  notify:
#    - Restart server
