- name: Install a few core modules
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - "python3"
    - "python3-pip"
    - "firewalld"
    - "unzip"
    - "nano"
  notify:
    - Restart server

- name: Start firewall service
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
    daemon_reload: true

